remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: IceNet-AI
description: IceNet is a probabilistic, deep learning sea ice forecasting system developed by an international team and led by British Antarctic Survey and The Alan Turing Institute
